trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build stage
  jobs:  
	- stage: Build_dockerimage
	  displayName: Build and push image
	  jobs:  
	  - job: Build_api_dockerimage
		displayName: Build and push image
		steps:
		- task: Docker@2
		  displayName: Build and push an image
		  inputs:
			containerRegistry: 'TicTacToe.dockerhub.com'
			repository: 'TicTacToe'
			command: 'buildAndPush'
			Dockerfile: '$(Build.SourcesDirectory)/dockerfile'
			tags: '$(Build.BuildId)'
	  - job: Build_java_dockerimage
		displayName: Build and push image
		steps:
		- task: Docker@2
		  displayName: Build and push an image
		  inputs:
			containerRegistry: 'TicTacToe.dockerhub.com'
			repository: 'TicTacToe'
			command: 'buildAndPush'
			Dockerfile: '$(Build.SourcesDirectory)/dockerfile'
			tags: '$(Build.BuildId)'
